[context.production.environment]
HUGO_VERSION = "0.64.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1.environment]
HUGO_VERSION = "0.64.1"
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_VERSION = "0.64.1"

[context.branch-deploy.environment]
HUGO_VERSION = "0.64.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

HUGO_VERSION = "0.64.1"